server {
    listen 80;
    server_name _;
    
    # ACME Challenge for Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all HTTP traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# Example of how services will be configured (this will be in conf.d/)
# Each service will provide its own file like rabbitmq.conf
